version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=users
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'users'   
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'      
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"


volumes:
  mysql-data:
